apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stock.fullname" . }}-n8n-worker
  labels:
    {{- include "stock.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.services.n8nWorker.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}