apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock.fullname" . }}-n8n-worker
  labels:
    {{- include "stock.labels" . | nindent 4 }}
    {{- if .Values.services.n8nMain.enablePrometheusMetrics }}
      {{- include "stock.prometheusLabels" . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.services.n8nMain.enablePrometheusMetrics }}
  type: ClusterIP
  ports:
    - port: {{ .Values.services.n8nMain.containerPort | default 5678 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- else }}
  clusterIP: None
  {{- end }}
  selector:
    app: {{ include "stock.fullname" . }}-n8n-worker